apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ecr-public-login
spec:
  stepTemplate:
    env:
    - name: HOME
      value: /tekton/home
    envFrom:
    - secretRef:
        name: multiarch-builder-envvars
        optional: true
    name: ""
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 16Mi
    workingDir: /tekton/home
  steps:
  - name: ecr-public-login
    image: quay.io/krestomatio/ansible-docker-ci
    resources: {}
    script: |
      #!/bin/sh -eu
      pip install --user awscli
      $HOME/.local/bin/aws ecr-public get-login-password | docker login --username AWS --password-stdin public.ecr.aws
